# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20191128_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
    ]
